name: appmob
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  location: ^8.0.0
  url_launcher: ^6.1.11
  lucide_icons: ^0.257.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.3
  image_picker: ^0.8.5+3
  provider: ^6.1.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  shared_preferences: ^2.2.2
  
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  record: ^5.0.0

  uuid: ^4.0.0
  firebase_storage: ^12.4.5
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/amico.png
    - assets/logo9itari.png
    - assets/build.png
    - assets/usad.png
    - assets/translate/
